services:
  - type: web
    name: dkmn-backend
    env: docker
    plan: free
    region: singapore
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: dkmn-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: dkmn-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: dkmn-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: dkmn-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: dkmn-db
          property: password

databases:
  - name: dkmn-db
    plan: free
    databaseName: dkmn
    user: dkmn_user
    region: singapore
